# web:
#   image: dius/pact_broker
#   ports:
#    - "80:80"
#   links:
#    - postgres
#   environment:
#     PACT_BROKER_DATABASE_USERNAME: postgres
#     PACT_BROKER_DATABASE_PASSWORD: mysecretpassword
#     PACT_BROKER_DATABASE_HOST: postgres
#     PACT_BROKER_DATABASE_NAME: postgres
#   mem_limit: 128
postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: mysecretpassword
  # mem_limit: 256
